# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20161113_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(default='default-avatar.png', upload_to='files/%Y/%m/%d'),
        ),
    ]
