# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20161113_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.ImageField(upload_to='files'),
        ),
    ]
